# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: app_messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Debug_Level(betterproto.Enum):
    INFO = 0
    WARNING = 1
    ERROR = 2


@dataclass
class Debug(betterproto.Message):
    level: "Debug_Level" = betterproto.enum_field(1)
    msg: str = betterproto.string_field(2)


@dataclass
class Node_State(betterproto.Message):
    command_id: int = betterproto.uint32_field(1)
    command_data: str = betterproto.string_field(2)


@dataclass
class Communication(betterproto.Message):
    node_state: "Node_State" = betterproto.message_field(1, group="payload")
    debug_message: "Debug" = betterproto.message_field(2, group="payload")
