# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: app_messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Command(betterproto.Message):
    command_id: int = betterproto.uint32_field(1)
    command_data: str = betterproto.string_field(2)
