/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APP_APP_MESSAGES_PB_H_INCLUDED
#define PB_APP_APP_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _app_Debug_Level {
    app_Debug_Level_INFO = 0,
    app_Debug_Level_WARNING = 1,
    app_Debug_Level_ERROR = 2
} app_Debug_Level;

/* Struct definitions */
/* ========================== SHARED "TYPES" ==========================
the most standards-compliant way to define fixed-sized arrays, but also define them as optional
involves wrapping them in a message. Annoying, but it works.
sizes set in .options file */
typedef struct _app_uint32_2 {
    uint32_t values[2];
} app_uint32_2;

typedef struct _app_uint32_4 {
    uint32_t values[4];
} app_uint32_4;

typedef struct _app_uint32_10 {
    uint32_t values[10];
} app_uint32_10;

typedef struct _app_bool_4 {
    bool values[4];
} app_bool_4;

typedef struct _app_Debug {
    app_Debug_Level level;
    char msg[256]; /* max length set in .options file, 256 */
} app_Debug;

/* ### STATE SUPERVISOR ### */
typedef struct _app_State_Supervisor_Status {
    bool decode_err;
    uint32_t decode_err_deserz;
    uint32_t decode_err_magic;
    uint32_t decode_err_msgtype;
    bool encode_err;
    uint32_t encode_err_serz;
} app_State_Supervisor_Status;

typedef struct _app_State_Supervisor {
    app_State_Supervisor_Status status; /* no commands */
} app_State_Supervisor;

/* ### MULTICARD INFORMATION ### */
typedef struct _app_Multicard_Status {
    bool all_present;
    uint32_t node_id;
} app_Multicard_Status;

typedef struct _app_Multicard_Command {
    bool has_sel_pd_input_aux_npic;
    bool sel_pd_input_aux_npic;
} app_Multicard_Command;

typedef struct _app_Multicard {
    app_Multicard_Status status;
    bool has_command;
    app_Multicard_Command command;
} app_Multicard;

/* ### POWER MONITOR ### */
typedef struct _app_PM_Status {
    bool immediate_power_status;
    bool debounced_power_status;
} app_PM_Status;

typedef struct _app_PM_Command {
    bool has_regulator_enable;
    bool regulator_enable;
} app_PM_Command;

typedef struct _app_PM {
    app_PM_Status status;
    bool has_command;
    app_PM_Command command;
} app_PM;

typedef struct _app_Offset_Ctrl_Status {
    bool device_present;
    bool device_error;
    app_uint32_4 offset_readback; /* array of 4 uint32s */
} app_Offset_Ctrl_Status;

typedef struct _app_Offset_Ctrl_Command {
    bool has_do_readback;
    bool do_readback;
    bool has_offset_set;
    app_uint32_4 offset_set;
} app_Offset_Ctrl_Command;

typedef struct _app_Offset_Ctrl {
    app_Offset_Ctrl_Status status;
    bool has_command;
    app_Offset_Ctrl_Command command;
} app_Offset_Ctrl;

/* ### HISPEED SUBSYSTEM ### */
typedef struct _app_Hispeed_Status {
    bool armed;
    bool done_success;
    bool done_err_ready;
    bool done_err_timeout;
    bool done_err_pwr;
    bool done_err_cancelled;
    app_uint32_4 tia_adc_readback;
} app_Hispeed_Status;

typedef struct _app_Hispeed_Command {
    bool has_arm_request;
    bool arm_request;
    bool has_load_test_sequence;
    bool load_test_sequence;
    bool has_SOA_enable;
    app_bool_4 SOA_enable;
    bool has_TIA_enable;
    app_bool_4 TIA_enable;
    bool has_SOA_DAC_drive;
    app_uint32_4 SOA_DAC_drive;
} app_Hispeed_Command;

typedef struct _app_Hispeed {
    app_Hispeed_Status status;
    bool has_command;
    app_Hispeed_Command command;
} app_Hispeed;

/* ### CoB TEMPERATURE ### */
typedef struct _app_CoB_Temp_Status {
    bool device_present;
    bool device_error;
    uint32_t device_id;
    float temperature_celsius;
} app_CoB_Temp_Status;

typedef struct _app_CoB_Temp {
    app_CoB_Temp_Status status; /* no commands */
} app_CoB_Temp;

/* ### CoB EEPROM ### */
typedef struct _app_CoB_EEPROM_Status {
    bool device_present;
    bool device_error;
    uint32_t cob_UID;
    char cob_desc[128]; /* max length set in .options file, 128 */
} app_CoB_EEPROM_Status;

typedef struct _app_CoB_EEPROM_Command {
    bool has_do_cob_write_desc;
    bool do_cob_write_desc;
    bool has_cob_desc_set;
    char cob_desc_set[128]; /* max length set in .options file, 128 */
    bool has_cob_write_key;
    uint32_t cob_write_key;
} app_CoB_EEPROM_Command;

typedef struct _app_CoB_EEPROM {
    app_CoB_EEPROM_Status status;
    bool has_command;
    app_CoB_EEPROM_Command command;
} app_CoB_EEPROM;

/* ### WAVEGUIDE BIAS DRIVES ### */
typedef struct _app_WG_Bias_Setpoints {
    app_uint32_10 stub_setpoint;
    app_uint32_4 mid_setpoint;
    app_uint32_2 bulk_setpoint;
} app_WG_Bias_Setpoints;

typedef struct _app_WG_Bias_Status {
    bool device_present;
    bool device_error;
    app_WG_Bias_Setpoints setpoints_readback;
} app_WG_Bias_Status;

typedef struct _app_WG_Bias_Command {
    bool has_setpoints;
    app_WG_Bias_Setpoints setpoints;
    bool has_regulator_enable;
    bool regulator_enable;
    bool has_do_readback;
    bool do_readback;
} app_WG_Bias_Command;

typedef struct _app_WG_Bias {
    app_WG_Bias_Status status;
    bool has_command;
    app_WG_Bias_Command command;
} app_WG_Bias;

/* ### NEURAL MEMORY INTERFACE ### */
typedef struct _app_Neural_Mem_Status {
    uint32_t detected_input_size;
    uint32_t detected_output_size;
    bool mem_attached;
} app_Neural_Mem_Status;

typedef struct _app_Neural_Mem_Command {
    bool has_check_io_size;
    bool check_io_size;
    bool has_load_test_pattern;
    uint32_t load_test_pattern;
} app_Neural_Mem_Command;

typedef struct _app_Neural_Mem {
    app_Neural_Mem_Status status;
    bool has_command;
    app_Neural_Mem_Command command;
} app_Neural_Mem;

/* ### COMMS INTERFACE ### */
typedef struct _app_Comms_Status {
    bool comms_connected;
} app_Comms_Status;

typedef struct _app_Comms_Command {
    bool has_allow_connection;
    bool allow_connection;
} app_Comms_Command;

typedef struct _app_Comms {
    app_Comms_Status status;
    bool has_command;
    app_Comms_Command command;
} app_Comms;

typedef struct _app_Node_State {
    app_State_Supervisor state_supervisor;
    app_Multicard multicard;
    app_PM pm_onboard;
    app_PM pm_motherboard;
    app_Offset_Ctrl offset_ctrl;
    app_Hispeed hispeed;
    app_CoB_Temp cob_temp;
    app_CoB_EEPROM cob_eeprom;
    app_WG_Bias waveguide_bias;
    app_Neural_Mem neural_mem_manager;
    app_Comms comms;
    uint32_t MAGIC_NUMBER;
    bool has_do_system_reset;
    bool do_system_reset;
} app_Node_State;

typedef struct _app_Communication {
    pb_size_t which_payload;
    union {
        app_Node_State node_state;
        app_Debug debug_message;
    } payload;
} app_Communication;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _app_Debug_Level_MIN app_Debug_Level_INFO
#define _app_Debug_Level_MAX app_Debug_Level_ERROR
#define _app_Debug_Level_ARRAYSIZE ((app_Debug_Level)(app_Debug_Level_ERROR+1))





#define app_Debug_level_ENUMTYPE app_Debug_Level

































/* Initializer values for message structs */
#define app_uint32_2_init_default                {{0, 0}}
#define app_uint32_4_init_default                {{0, 0, 0, 0}}
#define app_uint32_10_init_default               {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define app_bool_4_init_default                  {{0, 0, 0, 0}}
#define app_Debug_init_default                   {_app_Debug_Level_MIN, ""}
#define app_State_Supervisor_Status_init_default {0, 0, 0, 0, 0, 0}
#define app_State_Supervisor_init_default        {app_State_Supervisor_Status_init_default}
#define app_Multicard_Status_init_default        {0, 0}
#define app_Multicard_Command_init_default       {false, 0}
#define app_Multicard_init_default               {app_Multicard_Status_init_default, false, app_Multicard_Command_init_default}
#define app_PM_Status_init_default               {0, 0}
#define app_PM_Command_init_default              {false, 0}
#define app_PM_init_default                      {app_PM_Status_init_default, false, app_PM_Command_init_default}
#define app_Offset_Ctrl_Status_init_default      {0, 0, app_uint32_4_init_default}
#define app_Offset_Ctrl_Command_init_default     {false, 0, false, app_uint32_4_init_default}
#define app_Offset_Ctrl_init_default             {app_Offset_Ctrl_Status_init_default, false, app_Offset_Ctrl_Command_init_default}
#define app_Hispeed_Status_init_default          {0, 0, 0, 0, 0, 0, app_uint32_4_init_default}
#define app_Hispeed_Command_init_default         {false, 0, false, 0, false, app_bool_4_init_default, false, app_bool_4_init_default, false, app_uint32_4_init_default}
#define app_Hispeed_init_default                 {app_Hispeed_Status_init_default, false, app_Hispeed_Command_init_default}
#define app_CoB_Temp_Status_init_default         {0, 0, 0, 0}
#define app_CoB_Temp_init_default                {app_CoB_Temp_Status_init_default}
#define app_CoB_EEPROM_Status_init_default       {0, 0, 0, ""}
#define app_CoB_EEPROM_Command_init_default      {false, 0, false, "", false, 0}
#define app_CoB_EEPROM_init_default              {app_CoB_EEPROM_Status_init_default, false, app_CoB_EEPROM_Command_init_default}
#define app_WG_Bias_Setpoints_init_default       {app_uint32_10_init_default, app_uint32_4_init_default, app_uint32_2_init_default}
#define app_WG_Bias_Status_init_default          {0, 0, app_WG_Bias_Setpoints_init_default}
#define app_WG_Bias_Command_init_default         {false, app_WG_Bias_Setpoints_init_default, false, 0, false, 0}
#define app_WG_Bias_init_default                 {app_WG_Bias_Status_init_default, false, app_WG_Bias_Command_init_default}
#define app_Neural_Mem_Status_init_default       {0, 0, 0}
#define app_Neural_Mem_Command_init_default      {false, 0, false, 0}
#define app_Neural_Mem_init_default              {app_Neural_Mem_Status_init_default, false, app_Neural_Mem_Command_init_default}
#define app_Comms_Status_init_default            {0}
#define app_Comms_Command_init_default           {false, 0}
#define app_Comms_init_default                   {app_Comms_Status_init_default, false, app_Comms_Command_init_default}
#define app_Node_State_init_default              {app_State_Supervisor_init_default, app_Multicard_init_default, app_PM_init_default, app_PM_init_default, app_Offset_Ctrl_init_default, app_Hispeed_init_default, app_CoB_Temp_init_default, app_CoB_EEPROM_init_default, app_WG_Bias_init_default, app_Neural_Mem_init_default, app_Comms_init_default, 0, false, 0}
#define app_Communication_init_default           {0, {app_Node_State_init_default}}
#define app_uint32_2_init_zero                   {{0, 0}}
#define app_uint32_4_init_zero                   {{0, 0, 0, 0}}
#define app_uint32_10_init_zero                  {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define app_bool_4_init_zero                     {{0, 0, 0, 0}}
#define app_Debug_init_zero                      {_app_Debug_Level_MIN, ""}
#define app_State_Supervisor_Status_init_zero    {0, 0, 0, 0, 0, 0}
#define app_State_Supervisor_init_zero           {app_State_Supervisor_Status_init_zero}
#define app_Multicard_Status_init_zero           {0, 0}
#define app_Multicard_Command_init_zero          {false, 0}
#define app_Multicard_init_zero                  {app_Multicard_Status_init_zero, false, app_Multicard_Command_init_zero}
#define app_PM_Status_init_zero                  {0, 0}
#define app_PM_Command_init_zero                 {false, 0}
#define app_PM_init_zero                         {app_PM_Status_init_zero, false, app_PM_Command_init_zero}
#define app_Offset_Ctrl_Status_init_zero         {0, 0, app_uint32_4_init_zero}
#define app_Offset_Ctrl_Command_init_zero        {false, 0, false, app_uint32_4_init_zero}
#define app_Offset_Ctrl_init_zero                {app_Offset_Ctrl_Status_init_zero, false, app_Offset_Ctrl_Command_init_zero}
#define app_Hispeed_Status_init_zero             {0, 0, 0, 0, 0, 0, app_uint32_4_init_zero}
#define app_Hispeed_Command_init_zero            {false, 0, false, 0, false, app_bool_4_init_zero, false, app_bool_4_init_zero, false, app_uint32_4_init_zero}
#define app_Hispeed_init_zero                    {app_Hispeed_Status_init_zero, false, app_Hispeed_Command_init_zero}
#define app_CoB_Temp_Status_init_zero            {0, 0, 0, 0}
#define app_CoB_Temp_init_zero                   {app_CoB_Temp_Status_init_zero}
#define app_CoB_EEPROM_Status_init_zero          {0, 0, 0, ""}
#define app_CoB_EEPROM_Command_init_zero         {false, 0, false, "", false, 0}
#define app_CoB_EEPROM_init_zero                 {app_CoB_EEPROM_Status_init_zero, false, app_CoB_EEPROM_Command_init_zero}
#define app_WG_Bias_Setpoints_init_zero          {app_uint32_10_init_zero, app_uint32_4_init_zero, app_uint32_2_init_zero}
#define app_WG_Bias_Status_init_zero             {0, 0, app_WG_Bias_Setpoints_init_zero}
#define app_WG_Bias_Command_init_zero            {false, app_WG_Bias_Setpoints_init_zero, false, 0, false, 0}
#define app_WG_Bias_init_zero                    {app_WG_Bias_Status_init_zero, false, app_WG_Bias_Command_init_zero}
#define app_Neural_Mem_Status_init_zero          {0, 0, 0}
#define app_Neural_Mem_Command_init_zero         {false, 0, false, 0}
#define app_Neural_Mem_init_zero                 {app_Neural_Mem_Status_init_zero, false, app_Neural_Mem_Command_init_zero}
#define app_Comms_Status_init_zero               {0}
#define app_Comms_Command_init_zero              {false, 0}
#define app_Comms_init_zero                      {app_Comms_Status_init_zero, false, app_Comms_Command_init_zero}
#define app_Node_State_init_zero                 {app_State_Supervisor_init_zero, app_Multicard_init_zero, app_PM_init_zero, app_PM_init_zero, app_Offset_Ctrl_init_zero, app_Hispeed_init_zero, app_CoB_Temp_init_zero, app_CoB_EEPROM_init_zero, app_WG_Bias_init_zero, app_Neural_Mem_init_zero, app_Comms_init_zero, 0, false, 0}
#define app_Communication_init_zero              {0, {app_Node_State_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define app_uint32_2_values_tag                  1
#define app_uint32_4_values_tag                  1
#define app_uint32_10_values_tag                 1
#define app_bool_4_values_tag                    1
#define app_Debug_level_tag                      1
#define app_Debug_msg_tag                        2
#define app_State_Supervisor_Status_decode_err_tag 1
#define app_State_Supervisor_Status_decode_err_deserz_tag 2
#define app_State_Supervisor_Status_decode_err_magic_tag 3
#define app_State_Supervisor_Status_decode_err_msgtype_tag 4
#define app_State_Supervisor_Status_encode_err_tag 5
#define app_State_Supervisor_Status_encode_err_serz_tag 6
#define app_State_Supervisor_status_tag          1
#define app_Multicard_Status_all_present_tag     1
#define app_Multicard_Status_node_id_tag         2
#define app_Multicard_Command_sel_pd_input_aux_npic_tag 1
#define app_Multicard_status_tag                 1
#define app_Multicard_command_tag                2
#define app_PM_Status_immediate_power_status_tag 1
#define app_PM_Status_debounced_power_status_tag 2
#define app_PM_Command_regulator_enable_tag      1
#define app_PM_status_tag                        1
#define app_PM_command_tag                       2
#define app_Offset_Ctrl_Status_device_present_tag 1
#define app_Offset_Ctrl_Status_device_error_tag  2
#define app_Offset_Ctrl_Status_offset_readback_tag 3
#define app_Offset_Ctrl_Command_do_readback_tag  1
#define app_Offset_Ctrl_Command_offset_set_tag   2
#define app_Offset_Ctrl_status_tag               1
#define app_Offset_Ctrl_command_tag              2
#define app_Hispeed_Status_armed_tag             1
#define app_Hispeed_Status_done_success_tag      2
#define app_Hispeed_Status_done_err_ready_tag    3
#define app_Hispeed_Status_done_err_timeout_tag  4
#define app_Hispeed_Status_done_err_pwr_tag      5
#define app_Hispeed_Status_done_err_cancelled_tag 6
#define app_Hispeed_Status_tia_adc_readback_tag  7
#define app_Hispeed_Command_arm_request_tag      1
#define app_Hispeed_Command_load_test_sequence_tag 2
#define app_Hispeed_Command_SOA_enable_tag       3
#define app_Hispeed_Command_TIA_enable_tag       4
#define app_Hispeed_Command_SOA_DAC_drive_tag    5
#define app_Hispeed_status_tag                   1
#define app_Hispeed_command_tag                  2
#define app_CoB_Temp_Status_device_present_tag   1
#define app_CoB_Temp_Status_device_error_tag     2
#define app_CoB_Temp_Status_device_id_tag        3
#define app_CoB_Temp_Status_temperature_celsius_tag 4
#define app_CoB_Temp_status_tag                  1
#define app_CoB_EEPROM_Status_device_present_tag 1
#define app_CoB_EEPROM_Status_device_error_tag   2
#define app_CoB_EEPROM_Status_cob_UID_tag        3
#define app_CoB_EEPROM_Status_cob_desc_tag       4
#define app_CoB_EEPROM_Command_do_cob_write_desc_tag 1
#define app_CoB_EEPROM_Command_cob_desc_set_tag  2
#define app_CoB_EEPROM_Command_cob_write_key_tag 3
#define app_CoB_EEPROM_status_tag                1
#define app_CoB_EEPROM_command_tag               2
#define app_WG_Bias_Setpoints_stub_setpoint_tag  1
#define app_WG_Bias_Setpoints_mid_setpoint_tag   2
#define app_WG_Bias_Setpoints_bulk_setpoint_tag  3
#define app_WG_Bias_Status_device_present_tag    1
#define app_WG_Bias_Status_device_error_tag      2
#define app_WG_Bias_Status_setpoints_readback_tag 3
#define app_WG_Bias_Command_setpoints_tag        1
#define app_WG_Bias_Command_regulator_enable_tag 2
#define app_WG_Bias_Command_do_readback_tag      3
#define app_WG_Bias_status_tag                   1
#define app_WG_Bias_command_tag                  2
#define app_Neural_Mem_Status_detected_input_size_tag 1
#define app_Neural_Mem_Status_detected_output_size_tag 2
#define app_Neural_Mem_Status_mem_attached_tag   3
#define app_Neural_Mem_Command_check_io_size_tag 1
#define app_Neural_Mem_Command_load_test_pattern_tag 2
#define app_Neural_Mem_status_tag                1
#define app_Neural_Mem_command_tag               2
#define app_Comms_Status_comms_connected_tag     1
#define app_Comms_Command_allow_connection_tag   1
#define app_Comms_status_tag                     1
#define app_Comms_command_tag                    2
#define app_Node_State_state_supervisor_tag      1
#define app_Node_State_multicard_tag             2
#define app_Node_State_pm_onboard_tag            3
#define app_Node_State_pm_motherboard_tag        4
#define app_Node_State_offset_ctrl_tag           5
#define app_Node_State_hispeed_tag               6
#define app_Node_State_cob_temp_tag              7
#define app_Node_State_cob_eeprom_tag            8
#define app_Node_State_waveguide_bias_tag        9
#define app_Node_State_neural_mem_manager_tag    10
#define app_Node_State_comms_tag                 11
#define app_Node_State_MAGIC_NUMBER_tag          12
#define app_Node_State_do_system_reset_tag       13
#define app_Communication_node_state_tag         1
#define app_Communication_debug_message_tag      2

/* Struct field encoding specification for nanopb */
#define app_uint32_2_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   values,            1)
#define app_uint32_2_CALLBACK NULL
#define app_uint32_2_DEFAULT NULL

#define app_uint32_4_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   values,            1)
#define app_uint32_4_CALLBACK NULL
#define app_uint32_4_DEFAULT NULL

#define app_uint32_10_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   values,            1)
#define app_uint32_10_CALLBACK NULL
#define app_uint32_10_DEFAULT NULL

#define app_bool_4_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, BOOL,     values,            1)
#define app_bool_4_CALLBACK NULL
#define app_bool_4_DEFAULT NULL

#define app_Debug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    level,             1) \
X(a, STATIC,   SINGULAR, STRING,   msg,               2)
#define app_Debug_CALLBACK NULL
#define app_Debug_DEFAULT NULL

#define app_State_Supervisor_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     decode_err,        1) \
X(a, STATIC,   SINGULAR, UINT32,   decode_err_deserz,   2) \
X(a, STATIC,   SINGULAR, UINT32,   decode_err_magic,   3) \
X(a, STATIC,   SINGULAR, UINT32,   decode_err_msgtype,   4) \
X(a, STATIC,   SINGULAR, BOOL,     encode_err,        5) \
X(a, STATIC,   SINGULAR, UINT32,   encode_err_serz,   6)
#define app_State_Supervisor_Status_CALLBACK NULL
#define app_State_Supervisor_Status_DEFAULT NULL

#define app_State_Supervisor_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1)
#define app_State_Supervisor_CALLBACK NULL
#define app_State_Supervisor_DEFAULT NULL
#define app_State_Supervisor_status_MSGTYPE app_State_Supervisor_Status

#define app_Multicard_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     all_present,       1) \
X(a, STATIC,   SINGULAR, UINT32,   node_id,           2)
#define app_Multicard_Status_CALLBACK NULL
#define app_Multicard_Status_DEFAULT NULL

#define app_Multicard_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     sel_pd_input_aux_npic,   1)
#define app_Multicard_Command_CALLBACK NULL
#define app_Multicard_Command_DEFAULT NULL

#define app_Multicard_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_Multicard_CALLBACK NULL
#define app_Multicard_DEFAULT NULL
#define app_Multicard_status_MSGTYPE app_Multicard_Status
#define app_Multicard_command_MSGTYPE app_Multicard_Command

#define app_PM_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     immediate_power_status,   1) \
X(a, STATIC,   SINGULAR, BOOL,     debounced_power_status,   2)
#define app_PM_Status_CALLBACK NULL
#define app_PM_Status_DEFAULT NULL

#define app_PM_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     regulator_enable,   1)
#define app_PM_Command_CALLBACK NULL
#define app_PM_Command_DEFAULT NULL

#define app_PM_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_PM_CALLBACK NULL
#define app_PM_DEFAULT NULL
#define app_PM_status_MSGTYPE app_PM_Status
#define app_PM_command_MSGTYPE app_PM_Command

#define app_Offset_Ctrl_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     device_present,    1) \
X(a, STATIC,   SINGULAR, BOOL,     device_error,      2) \
X(a, STATIC,   REQUIRED, MESSAGE,  offset_readback,   3)
#define app_Offset_Ctrl_Status_CALLBACK NULL
#define app_Offset_Ctrl_Status_DEFAULT NULL
#define app_Offset_Ctrl_Status_offset_readback_MSGTYPE app_uint32_4

#define app_Offset_Ctrl_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     do_readback,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  offset_set,        2)
#define app_Offset_Ctrl_Command_CALLBACK NULL
#define app_Offset_Ctrl_Command_DEFAULT NULL
#define app_Offset_Ctrl_Command_offset_set_MSGTYPE app_uint32_4

#define app_Offset_Ctrl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_Offset_Ctrl_CALLBACK NULL
#define app_Offset_Ctrl_DEFAULT NULL
#define app_Offset_Ctrl_status_MSGTYPE app_Offset_Ctrl_Status
#define app_Offset_Ctrl_command_MSGTYPE app_Offset_Ctrl_Command

#define app_Hispeed_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     armed,             1) \
X(a, STATIC,   SINGULAR, BOOL,     done_success,      2) \
X(a, STATIC,   SINGULAR, BOOL,     done_err_ready,    3) \
X(a, STATIC,   SINGULAR, BOOL,     done_err_timeout,   4) \
X(a, STATIC,   SINGULAR, BOOL,     done_err_pwr,      5) \
X(a, STATIC,   SINGULAR, BOOL,     done_err_cancelled,   6) \
X(a, STATIC,   REQUIRED, MESSAGE,  tia_adc_readback,   7)
#define app_Hispeed_Status_CALLBACK NULL
#define app_Hispeed_Status_DEFAULT NULL
#define app_Hispeed_Status_tia_adc_readback_MSGTYPE app_uint32_4

#define app_Hispeed_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     arm_request,       1) \
X(a, STATIC,   OPTIONAL, BOOL,     load_test_sequence,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  SOA_enable,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  TIA_enable,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  SOA_DAC_drive,     5)
#define app_Hispeed_Command_CALLBACK NULL
#define app_Hispeed_Command_DEFAULT NULL
#define app_Hispeed_Command_SOA_enable_MSGTYPE app_bool_4
#define app_Hispeed_Command_TIA_enable_MSGTYPE app_bool_4
#define app_Hispeed_Command_SOA_DAC_drive_MSGTYPE app_uint32_4

#define app_Hispeed_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_Hispeed_CALLBACK NULL
#define app_Hispeed_DEFAULT NULL
#define app_Hispeed_status_MSGTYPE app_Hispeed_Status
#define app_Hispeed_command_MSGTYPE app_Hispeed_Command

#define app_CoB_Temp_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     device_present,    1) \
X(a, STATIC,   SINGULAR, BOOL,     device_error,      2) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_celsius,   4)
#define app_CoB_Temp_Status_CALLBACK NULL
#define app_CoB_Temp_Status_DEFAULT NULL

#define app_CoB_Temp_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1)
#define app_CoB_Temp_CALLBACK NULL
#define app_CoB_Temp_DEFAULT NULL
#define app_CoB_Temp_status_MSGTYPE app_CoB_Temp_Status

#define app_CoB_EEPROM_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     device_present,    1) \
X(a, STATIC,   SINGULAR, BOOL,     device_error,      2) \
X(a, STATIC,   SINGULAR, UINT32,   cob_UID,           3) \
X(a, STATIC,   SINGULAR, STRING,   cob_desc,          4)
#define app_CoB_EEPROM_Status_CALLBACK NULL
#define app_CoB_EEPROM_Status_DEFAULT NULL

#define app_CoB_EEPROM_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     do_cob_write_desc,   1) \
X(a, STATIC,   OPTIONAL, STRING,   cob_desc_set,      2) \
X(a, STATIC,   OPTIONAL, UINT32,   cob_write_key,     3)
#define app_CoB_EEPROM_Command_CALLBACK NULL
#define app_CoB_EEPROM_Command_DEFAULT NULL

#define app_CoB_EEPROM_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_CoB_EEPROM_CALLBACK NULL
#define app_CoB_EEPROM_DEFAULT NULL
#define app_CoB_EEPROM_status_MSGTYPE app_CoB_EEPROM_Status
#define app_CoB_EEPROM_command_MSGTYPE app_CoB_EEPROM_Command

#define app_WG_Bias_Setpoints_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  stub_setpoint,     1) \
X(a, STATIC,   REQUIRED, MESSAGE,  mid_setpoint,      2) \
X(a, STATIC,   REQUIRED, MESSAGE,  bulk_setpoint,     3)
#define app_WG_Bias_Setpoints_CALLBACK NULL
#define app_WG_Bias_Setpoints_DEFAULT NULL
#define app_WG_Bias_Setpoints_stub_setpoint_MSGTYPE app_uint32_10
#define app_WG_Bias_Setpoints_mid_setpoint_MSGTYPE app_uint32_4
#define app_WG_Bias_Setpoints_bulk_setpoint_MSGTYPE app_uint32_2

#define app_WG_Bias_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     device_present,    1) \
X(a, STATIC,   SINGULAR, BOOL,     device_error,      2) \
X(a, STATIC,   REQUIRED, MESSAGE,  setpoints_readback,   3)
#define app_WG_Bias_Status_CALLBACK NULL
#define app_WG_Bias_Status_DEFAULT NULL
#define app_WG_Bias_Status_setpoints_readback_MSGTYPE app_WG_Bias_Setpoints

#define app_WG_Bias_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  setpoints,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     regulator_enable,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     do_readback,       3)
#define app_WG_Bias_Command_CALLBACK NULL
#define app_WG_Bias_Command_DEFAULT NULL
#define app_WG_Bias_Command_setpoints_MSGTYPE app_WG_Bias_Setpoints

#define app_WG_Bias_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_WG_Bias_CALLBACK NULL
#define app_WG_Bias_DEFAULT NULL
#define app_WG_Bias_status_MSGTYPE app_WG_Bias_Status
#define app_WG_Bias_command_MSGTYPE app_WG_Bias_Command

#define app_Neural_Mem_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   detected_input_size,   1) \
X(a, STATIC,   SINGULAR, UINT32,   detected_output_size,   2) \
X(a, STATIC,   SINGULAR, BOOL,     mem_attached,      3)
#define app_Neural_Mem_Status_CALLBACK NULL
#define app_Neural_Mem_Status_DEFAULT NULL

#define app_Neural_Mem_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     check_io_size,     1) \
X(a, STATIC,   OPTIONAL, UINT32,   load_test_pattern,   2)
#define app_Neural_Mem_Command_CALLBACK NULL
#define app_Neural_Mem_Command_DEFAULT NULL

#define app_Neural_Mem_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_Neural_Mem_CALLBACK NULL
#define app_Neural_Mem_DEFAULT NULL
#define app_Neural_Mem_status_MSGTYPE app_Neural_Mem_Status
#define app_Neural_Mem_command_MSGTYPE app_Neural_Mem_Command

#define app_Comms_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     comms_connected,   1)
#define app_Comms_Status_CALLBACK NULL
#define app_Comms_Status_DEFAULT NULL

#define app_Comms_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     allow_connection,   1)
#define app_Comms_Command_CALLBACK NULL
#define app_Comms_Command_DEFAULT NULL

#define app_Comms_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           2)
#define app_Comms_CALLBACK NULL
#define app_Comms_DEFAULT NULL
#define app_Comms_status_MSGTYPE app_Comms_Status
#define app_Comms_command_MSGTYPE app_Comms_Command

#define app_Node_State_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  state_supervisor,   1) \
X(a, STATIC,   REQUIRED, MESSAGE,  multicard,         2) \
X(a, STATIC,   REQUIRED, MESSAGE,  pm_onboard,        3) \
X(a, STATIC,   REQUIRED, MESSAGE,  pm_motherboard,    4) \
X(a, STATIC,   REQUIRED, MESSAGE,  offset_ctrl,       5) \
X(a, STATIC,   REQUIRED, MESSAGE,  hispeed,           6) \
X(a, STATIC,   REQUIRED, MESSAGE,  cob_temp,          7) \
X(a, STATIC,   REQUIRED, MESSAGE,  cob_eeprom,        8) \
X(a, STATIC,   REQUIRED, MESSAGE,  waveguide_bias,    9) \
X(a, STATIC,   REQUIRED, MESSAGE,  neural_mem_manager,  10) \
X(a, STATIC,   REQUIRED, MESSAGE,  comms,            11) \
X(a, STATIC,   SINGULAR, UINT32,   MAGIC_NUMBER,     12) \
X(a, STATIC,   OPTIONAL, BOOL,     do_system_reset,  13)
#define app_Node_State_CALLBACK NULL
#define app_Node_State_DEFAULT NULL
#define app_Node_State_state_supervisor_MSGTYPE app_State_Supervisor
#define app_Node_State_multicard_MSGTYPE app_Multicard
#define app_Node_State_pm_onboard_MSGTYPE app_PM
#define app_Node_State_pm_motherboard_MSGTYPE app_PM
#define app_Node_State_offset_ctrl_MSGTYPE app_Offset_Ctrl
#define app_Node_State_hispeed_MSGTYPE app_Hispeed
#define app_Node_State_cob_temp_MSGTYPE app_CoB_Temp
#define app_Node_State_cob_eeprom_MSGTYPE app_CoB_EEPROM
#define app_Node_State_waveguide_bias_MSGTYPE app_WG_Bias
#define app_Node_State_neural_mem_manager_MSGTYPE app_Neural_Mem
#define app_Node_State_comms_MSGTYPE app_Comms

#define app_Communication_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,node_state,payload.node_state),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,debug_message,payload.debug_message),   2)
#define app_Communication_CALLBACK NULL
#define app_Communication_DEFAULT NULL
#define app_Communication_payload_node_state_MSGTYPE app_Node_State
#define app_Communication_payload_debug_message_MSGTYPE app_Debug

extern const pb_msgdesc_t app_uint32_2_msg;
extern const pb_msgdesc_t app_uint32_4_msg;
extern const pb_msgdesc_t app_uint32_10_msg;
extern const pb_msgdesc_t app_bool_4_msg;
extern const pb_msgdesc_t app_Debug_msg;
extern const pb_msgdesc_t app_State_Supervisor_Status_msg;
extern const pb_msgdesc_t app_State_Supervisor_msg;
extern const pb_msgdesc_t app_Multicard_Status_msg;
extern const pb_msgdesc_t app_Multicard_Command_msg;
extern const pb_msgdesc_t app_Multicard_msg;
extern const pb_msgdesc_t app_PM_Status_msg;
extern const pb_msgdesc_t app_PM_Command_msg;
extern const pb_msgdesc_t app_PM_msg;
extern const pb_msgdesc_t app_Offset_Ctrl_Status_msg;
extern const pb_msgdesc_t app_Offset_Ctrl_Command_msg;
extern const pb_msgdesc_t app_Offset_Ctrl_msg;
extern const pb_msgdesc_t app_Hispeed_Status_msg;
extern const pb_msgdesc_t app_Hispeed_Command_msg;
extern const pb_msgdesc_t app_Hispeed_msg;
extern const pb_msgdesc_t app_CoB_Temp_Status_msg;
extern const pb_msgdesc_t app_CoB_Temp_msg;
extern const pb_msgdesc_t app_CoB_EEPROM_Status_msg;
extern const pb_msgdesc_t app_CoB_EEPROM_Command_msg;
extern const pb_msgdesc_t app_CoB_EEPROM_msg;
extern const pb_msgdesc_t app_WG_Bias_Setpoints_msg;
extern const pb_msgdesc_t app_WG_Bias_Status_msg;
extern const pb_msgdesc_t app_WG_Bias_Command_msg;
extern const pb_msgdesc_t app_WG_Bias_msg;
extern const pb_msgdesc_t app_Neural_Mem_Status_msg;
extern const pb_msgdesc_t app_Neural_Mem_Command_msg;
extern const pb_msgdesc_t app_Neural_Mem_msg;
extern const pb_msgdesc_t app_Comms_Status_msg;
extern const pb_msgdesc_t app_Comms_Command_msg;
extern const pb_msgdesc_t app_Comms_msg;
extern const pb_msgdesc_t app_Node_State_msg;
extern const pb_msgdesc_t app_Communication_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define app_uint32_2_fields &app_uint32_2_msg
#define app_uint32_4_fields &app_uint32_4_msg
#define app_uint32_10_fields &app_uint32_10_msg
#define app_bool_4_fields &app_bool_4_msg
#define app_Debug_fields &app_Debug_msg
#define app_State_Supervisor_Status_fields &app_State_Supervisor_Status_msg
#define app_State_Supervisor_fields &app_State_Supervisor_msg
#define app_Multicard_Status_fields &app_Multicard_Status_msg
#define app_Multicard_Command_fields &app_Multicard_Command_msg
#define app_Multicard_fields &app_Multicard_msg
#define app_PM_Status_fields &app_PM_Status_msg
#define app_PM_Command_fields &app_PM_Command_msg
#define app_PM_fields &app_PM_msg
#define app_Offset_Ctrl_Status_fields &app_Offset_Ctrl_Status_msg
#define app_Offset_Ctrl_Command_fields &app_Offset_Ctrl_Command_msg
#define app_Offset_Ctrl_fields &app_Offset_Ctrl_msg
#define app_Hispeed_Status_fields &app_Hispeed_Status_msg
#define app_Hispeed_Command_fields &app_Hispeed_Command_msg
#define app_Hispeed_fields &app_Hispeed_msg
#define app_CoB_Temp_Status_fields &app_CoB_Temp_Status_msg
#define app_CoB_Temp_fields &app_CoB_Temp_msg
#define app_CoB_EEPROM_Status_fields &app_CoB_EEPROM_Status_msg
#define app_CoB_EEPROM_Command_fields &app_CoB_EEPROM_Command_msg
#define app_CoB_EEPROM_fields &app_CoB_EEPROM_msg
#define app_WG_Bias_Setpoints_fields &app_WG_Bias_Setpoints_msg
#define app_WG_Bias_Status_fields &app_WG_Bias_Status_msg
#define app_WG_Bias_Command_fields &app_WG_Bias_Command_msg
#define app_WG_Bias_fields &app_WG_Bias_msg
#define app_Neural_Mem_Status_fields &app_Neural_Mem_Status_msg
#define app_Neural_Mem_Command_fields &app_Neural_Mem_Command_msg
#define app_Neural_Mem_fields &app_Neural_Mem_msg
#define app_Comms_Status_fields &app_Comms_Status_msg
#define app_Comms_Command_fields &app_Comms_Command_msg
#define app_Comms_fields &app_Comms_msg
#define app_Node_State_fields &app_Node_State_msg
#define app_Communication_fields &app_Communication_msg

/* Maximum encoded size of messages (where known) */
#define APP_APP_MESSAGES_PB_H_MAX_SIZE           app_Communication_size
#define app_CoB_EEPROM_Command_size              138
#define app_CoB_EEPROM_Status_size               140
#define app_CoB_EEPROM_size                      284
#define app_CoB_Temp_Status_size                 15
#define app_CoB_Temp_size                        17
#define app_Comms_Command_size                   2
#define app_Comms_Status_size                    2
#define app_Comms_size                           8
#define app_Communication_size                   808
#define app_Debug_size                           260
#define app_Hispeed_Command_size                 50
#define app_Hispeed_Status_size                  38
#define app_Hispeed_size                         92
#define app_Multicard_Command_size               2
#define app_Multicard_Status_size                8
#define app_Multicard_size                       14
#define app_Neural_Mem_Command_size              8
#define app_Neural_Mem_Status_size               14
#define app_Neural_Mem_size                      26
#define app_Node_State_size                      805
#define app_Offset_Ctrl_Command_size             28
#define app_Offset_Ctrl_Status_size              30
#define app_Offset_Ctrl_size                     62
#define app_PM_Command_size                      2
#define app_PM_Status_size                       4
#define app_PM_size                              10
#define app_State_Supervisor_Status_size         28
#define app_State_Supervisor_size                30
#define app_WG_Bias_Command_size                 108
#define app_WG_Bias_Setpoints_size               102
#define app_WG_Bias_Status_size                  108
#define app_WG_Bias_size                         220
#define app_bool_4_size                          8
#define app_uint32_10_size                       60
#define app_uint32_2_size                        12
#define app_uint32_4_size                        24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
