/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "app_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(App_Debug, App_Debug, 2)


PB_BIND(App_Node_State, App_Node_State, AUTO)


PB_BIND(App_Communication, App_Communication, 2)





