# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: app_messages.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto


class DebugLevel(betterproto.Enum):
    INFO = 0
    WARNING = 1
    ERROR = 2


@dataclass(eq=False, repr=False)
class Uint322(betterproto.Message):
    """
    ========================== SHARED "TYPES" ==========================
    the most standards-compliant way to define fixed-sized arrays, but also define them as optional
    involves wrapping them in a message. Annoying, but it works.
    sizes set in .options file
    """

    values: List[int] = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class Uint324(betterproto.Message):
    values: List[int] = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class Uint3210(betterproto.Message):
    values: List[int] = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class Bool4(betterproto.Message):
    values: List[bool] = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class Debug(betterproto.Message):
    level: "DebugLevel" = betterproto.enum_field(1)
    msg: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class StateSupervisorStatus(betterproto.Message):
    """### STATE SUPERVISOR ###"""

    decode_err: bool = betterproto.bool_field(1)
    decode_err_deserz: int = betterproto.uint32_field(2)
    decode_err_magic: int = betterproto.uint32_field(3)
    decode_err_msgtype: int = betterproto.uint32_field(4)
    encode_err: bool = betterproto.bool_field(5)
    encode_err_serz: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class StateSupervisor(betterproto.Message):
    status: "StateSupervisorStatus" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class MulticardStatus(betterproto.Message):
    """### MULTICARD INFORMATION ###"""

    all_present: bool = betterproto.bool_field(1)
    node_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class MulticardCommand(betterproto.Message):
    sel_pd_input_aux_npic: Optional[bool] = betterproto.bool_field(1, optional=True)


@dataclass(eq=False, repr=False)
class Multicard(betterproto.Message):
    status: "MulticardStatus" = betterproto.message_field(1)
    command: "MulticardCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class PmStatus(betterproto.Message):
    """### POWER MONITOR ###"""

    immediate_power_status: bool = betterproto.bool_field(1)
    debounced_power_status: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class PmCommand(betterproto.Message):
    regulator_enable: Optional[bool] = betterproto.bool_field(1, optional=True)


@dataclass(eq=False, repr=False)
class Pm(betterproto.Message):
    status: "PmStatus" = betterproto.message_field(1)
    command: "PmCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class OffsetCtrlStatus(betterproto.Message):
    device_present: bool = betterproto.bool_field(1)
    device_error: bool = betterproto.bool_field(2)
    offset_readback: "Uint324" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class OffsetCtrlCommand(betterproto.Message):
    do_readback: Optional[bool] = betterproto.bool_field(1, optional=True)
    offset_set: Optional["Uint324"] = betterproto.message_field(2, optional=True)


@dataclass(eq=False, repr=False)
class OffsetCtrl(betterproto.Message):
    status: "OffsetCtrlStatus" = betterproto.message_field(1)
    command: "OffsetCtrlCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class HispeedStatus(betterproto.Message):
    """### HISPEED SUBSYSTEM ###"""

    armed: bool = betterproto.bool_field(1)
    done_success: bool = betterproto.bool_field(2)
    done_err_ready: bool = betterproto.bool_field(3)
    done_err_timeout: bool = betterproto.bool_field(4)
    done_err_pwr: bool = betterproto.bool_field(5)
    done_err_cancelled: bool = betterproto.bool_field(6)
    tia_adc_readback: "Uint324" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class HispeedCommand(betterproto.Message):
    arm_request: Optional[bool] = betterproto.bool_field(1, optional=True)
    load_test_sequence: Optional[bool] = betterproto.bool_field(2, optional=True)
    soa_enable: Optional["Bool4"] = betterproto.message_field(3, optional=True)
    tia_enable: Optional["Bool4"] = betterproto.message_field(4, optional=True)
    soa_dac_drive: Optional["Uint324"] = betterproto.message_field(5, optional=True)


@dataclass(eq=False, repr=False)
class Hispeed(betterproto.Message):
    status: "HispeedStatus" = betterproto.message_field(1)
    command: "HispeedCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CoBTempStatus(betterproto.Message):
    """### CoB TEMPERATURE ###"""

    device_present: bool = betterproto.bool_field(1)
    device_error: bool = betterproto.bool_field(2)
    device_id: int = betterproto.uint32_field(3)
    temperature_celsius: float = betterproto.float_field(4)


@dataclass(eq=False, repr=False)
class CoBTemp(betterproto.Message):
    status: "CoBTempStatus" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CoBEepromStatus(betterproto.Message):
    """### CoB EEPROM ###"""

    device_present: bool = betterproto.bool_field(1)
    device_error: bool = betterproto.bool_field(2)
    cob_uid: int = betterproto.uint32_field(3)
    cob_desc: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class CoBEepromCommand(betterproto.Message):
    do_cob_write_desc: Optional[bool] = betterproto.bool_field(1, optional=True)
    cob_desc_set: Optional[str] = betterproto.string_field(2, optional=True)
    cob_write_key: Optional[int] = betterproto.uint32_field(3, optional=True)


@dataclass(eq=False, repr=False)
class CoBEeprom(betterproto.Message):
    status: "CoBEepromStatus" = betterproto.message_field(1)
    command: "CoBEepromCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class WgBiasSetpoints(betterproto.Message):
    """### WAVEGUIDE BIAS DRIVES ###"""

    stub_setpoint: "Uint3210" = betterproto.message_field(1)
    mid_setpoint: "Uint324" = betterproto.message_field(2)
    bulk_setpoint: "Uint322" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class WgBiasStatus(betterproto.Message):
    device_present: bool = betterproto.bool_field(1)
    device_error: bool = betterproto.bool_field(2)
    setpoints_readback: "WgBiasSetpoints" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class WgBiasCommand(betterproto.Message):
    setpoints: Optional["WgBiasSetpoints"] = betterproto.message_field(1, optional=True)
    regulator_enable: Optional[bool] = betterproto.bool_field(2, optional=True)
    do_readback: Optional[bool] = betterproto.bool_field(3, optional=True)


@dataclass(eq=False, repr=False)
class WgBias(betterproto.Message):
    status: "WgBiasStatus" = betterproto.message_field(1)
    command: "WgBiasCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class NeuralMemStatus(betterproto.Message):
    """### NEURAL MEMORY INTERFACE ###"""

    detected_input_size: int = betterproto.uint32_field(1)
    detected_output_size: int = betterproto.uint32_field(2)
    mem_attached: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class NeuralMemCommand(betterproto.Message):
    check_io_size: Optional[bool] = betterproto.bool_field(1, optional=True)
    load_test_pattern: Optional[int] = betterproto.uint32_field(2, optional=True)


@dataclass(eq=False, repr=False)
class NeuralMem(betterproto.Message):
    status: "NeuralMemStatus" = betterproto.message_field(1)
    command: "NeuralMemCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CommsStatus(betterproto.Message):
    """### COMMS INTERFACE ###"""

    comms_connected: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CommsCommand(betterproto.Message):
    allow_connection: Optional[bool] = betterproto.bool_field(1, optional=True)


@dataclass(eq=False, repr=False)
class Comms(betterproto.Message):
    status: "CommsStatus" = betterproto.message_field(1)
    command: "CommsCommand" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class NodeState(betterproto.Message):
    state_supervisor: "StateSupervisor" = betterproto.message_field(1)
    multicard: "Multicard" = betterproto.message_field(2)
    pm_onboard: "Pm" = betterproto.message_field(3)
    pm_motherboard: "Pm" = betterproto.message_field(4)
    offset_ctrl: "OffsetCtrl" = betterproto.message_field(5)
    hispeed: "Hispeed" = betterproto.message_field(6)
    cob_temp: "CoBTemp" = betterproto.message_field(7)
    cob_eeprom: "CoBEeprom" = betterproto.message_field(8)
    waveguide_bias: "WgBias" = betterproto.message_field(9)
    neural_mem_manager: "NeuralMem" = betterproto.message_field(10)
    comms: "Comms" = betterproto.message_field(11)
    magic_number: int = betterproto.uint32_field(12)
    do_system_reset: Optional[bool] = betterproto.bool_field(13, optional=True)


@dataclass(eq=False, repr=False)
class Communication(betterproto.Message):
    node_state: "NodeState" = betterproto.message_field(1, group="payload")
    debug_message: "Debug" = betterproto.message_field(2, group="payload")
